import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "./components/shared/Navbar";
import Footer from "./components/shared/Footer";
import AuthProvider from "./authentication/AuthProvider";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata = {
  title: "Car Doctor Pro",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased bg-gray-100 min-h-screen`}
      >
        <AuthProvider>
          <div>
            <Navbar></Navbar>
          </div>
          {children}
          <div>
            <Footer></Footer>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
